export const  allRoles = [
    "Project Director",
    "Nuclear Engineer",
    "Civil Engineer",
    "Construction Manager",
    "Licensing Manager",
    "Regulatory Affairs Specialist",
    "Quality Assurance Manager",
    "Supply Chain Manager",
    "Health and Safety Manager",
    "Structural Engineer",
    "Commissioning Engineer",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Design Engineer",
    "Geotechnical Engineer",
    "Instrumentation and Control Engineer",
    "Risk Analyst",
    "Environmental Engineer",
    "Project Scheduler",
    "Cost Estimator",
    "Materials Engineer",
    "Fire Protection Engineer",
    "Turbine Engineer",
    "Radiation Protection Officer",
    "Operations Readiness Manager",
    "Program Director (Advanced Reactors)",
    "Systems Engineer",
    "Thermal Hydraulics Engineer",
    "Reactor Physics Analyst",
    "Fuel Cycle Analyst",
    "Control Room Designer",
    "Digital Instrumentation & Controls Engineer",
    "Human Factors Specialist",
    "Safety Analyst",
    "Integration Engineer",
    "Cybersecurity Analyst",
    "Modular Fabrication Manager",
    "Maintenance Engineer",
    "Start-up Engineer",
    "Economic Analyst",
    "Fusion Project Director",
    "Plasma Physicist",
    "Fusion Systems Engineer",
    "Superconducting Magnet Engineer",
    "Tritium Systems Engineer",
    "Fusion Reactor Design Lead",
    "Fusion Materials Scientist",
    "Fusion Safety Analyst",
    "Tokamak Operations Engineer",
    "Vacuum Systems Engineer",
    "Cryogenics Engineer",
    "RF Systems Engineer",
    "Fusion Fueling Engineer",
    "Divertor Systems Engineer",
    "Helium Cooling Systems Engineer",
    "Diagnostics and Instrumentation Engineer",
    "Neutronics Analyst",
    "Licensing Lead (Fusion)",
    "Control Systems Engineer (Fusion)",
    "Heat Recovery Engineer (Fusion)",
    "Decommissioning Project Manager",
    "Decommissioning Engineer",
    "Waste Characterization Specialist",
    "Radiological Survey Technician",
    "Decontamination Specialist",
    "Reactor Dismantling Engineer",
    "Environmental Remediation Manager",
    "Decommissioning Planner",
    "Demolition Engineer",
    "Radiological Control Technician",
    "Asbestos & Hazardous Material Specialist",
    "Field Supervisor (D&D)",
    "Cost Estimator (Decommissioning)",
    "Health Physics Technician",
    "Site Restoration Manager",
    "Waste Management Program Manager",
    "Waste Disposal Engineer",
    "Geological Repository Engineer",
    "Waste Form Specialist",
    "Transportation and Packaging Engineer",
    "Interim Storage Facility Manager",
    "Shielding Design Engineer",
    "Container Design Engineer",
    "Waste Treatment Systems Engineer",
    "Waste Compliance Analyst",
    "Radiological Assessor",
    "Nuclear Chemist",
    "Low-Level Waste Operations Technician",
    "High-Level Waste Systems Analyst",
    "Spent Fuel Pool Manager",
    "Dry Cask Storage Specialist",
    "Repository Licensing Manager",
    "Logistics Coordinator (Nuclear Waste)",
    "Waste Safety Officer",
    "Waste Policy Advisor",
    "Nuclear Policy Analyst",
    "Nuclear Finance Analyst",
    "Innovation Manager",
    "Public Engagement & Communications Manager",
    "Workforce Development Specialist"
  ];


  export const trxOffersYouCardItem = [
    {
        title:"Dedicated Nuclear Talent Advisory",
        para: "Industry-specific guidance on workforce planning, role design, and competitive positioning."
    },
    {
        title:"Candidate Lifecycle Management",
        para:"From attraction to onboarding and retention, we ensure that top talent stays engaged and aligned.",
    },
    {
        title:"Embedded Recruitment Solutions",
        para:"Onsite or remote delivery teams tailored to your internal processes and project dynamics.",
    },
    {
        title:"Market Benchmarking & Intelligence",
        para:"Insights into compensation, availability, skills trends, and regional labor market shifts.",
    },
    {
        title:"Precision Sourcing & Executive Search",
        para:"We go beyond job boards, using deep referral networks and sector intelligence to identify world-class professionals.",
    },
    {
        title:"Compliance & Security Awareness",
        para:"Our processes are built to support regulated environments, with candidate checks and protocols that reflect nuclear-grade diligence.",
    },
  ]

  export const nuclearCompanyChooseTrxCard = [
    {
        number: "01",
        title: "Global Nuclear Talent",
        desc1:
            "A curated, global candidate network focused exclusively on specialized nuclear roles",
    },
    {
        number: "02",
        title: "Sector-Savvy Teams",
        desc1:
            "Recruitment teams who understand your technical vocabulary, safety culture, and  challenges",

    },
    {
        number: "03",
        title: "Support Across Chain",
        desc1:
            "Flexibility to support EPCs, operators, regulators, research institutions, and supply chain partners",
    },
];
  


export const caseStudiesCardItem = [
    {
        date: "2019 – Present",
        title: "Kingdom of Saudi Arabia — First Commercial Nuclear Power Plant (2019 – Present)",
        client: "A regional radiopharmaceutical manufacturer launching new cyclotron and radiopharmacy sites",
        challenge: "The client needed to staff multiple sites across different countries with specialists qualified under diverse regulatory regimes, including GMP QPs and radiation protection advisors. The timeline was aggressive and required coordinated hires.",
        solution: ["On‑site workshop in Riyadh (November 2019) to map regulatory milestones, staffing levels, and organizational design for each project phase.", "Produced a bespoke Nuclear Workforce Roadmap covering 75 key positions across project management, licensing, and engineering disciplines.", "Activated our global talent network and delivered 150 screened CVs in < 30 days; 38% came from the wider GCC, 62% from Tier‑1 nuclear nations (UK, Canada, Korea, France).", "Embedded a bilingual TRX liaison on site to streamline security clearance and relocation logistics."],
        overCome: ["92 % of roles filled within eight weeks, allowing the client to freeze the Preliminary Safety Analysis Report on schedule.", "Accelerated FEED package approval by four months compared with baseline plan.", "Zero voluntary attrition after 24 months; several secondees have since transitioned into permanent Saudi‑national mentorship roles."],
    },
    {
        date: "2021 – present",
        title: "Poland — BWRX‑300 SMR Fleet Deployment (2021 – present)",
        client: "Private‑sector consortium developing the country’s first fleet of GE Hitachi BWRX‑300 Small Modular Reactors",
        challenge: "Challenge: With no domestic nuclear pedigree, the client required clarity on European regulatory expectations, salary benchmarks, and a hiring strategy that supported their owner‑operator responsibilities for up to ten SMRs.",
        solution: ["Market‑intelligence briefing in Warsaw covering EU nuclear new‑builds, permitting timelines, and talent availability across VVER, EPR, and AGR legacy fleets.", "Built a role matrix & compensation model aligned to Polish labour law and regional cost‑of‑living indices.", "Deployed a dedicated research cell that produced curated longlists for project controls, reactor island engineering, and quality management within two weeks."],
        overCome: ["Filled all first‑wave technical leadership posts (12 hires) in under 90 days.", "Salary model adopted as the basis for the client’s published EVP, improving offer‑acceptance rate to 88 %.", "Enabled the consortium to submit its site‑specific licence application six months ahead of schedule."],
    },
    {
        date: "2020 – Present",
        title: "United Kingdom — SMR Licensing Specialists (2020 – present)",
        client: "Confidential UK SMR developer",
        challenge: "Negotiating the Office for Nuclear Regulation (ONR) Generic Design Assessment demands seasoned professionals. The UK talent pool is finite and heavily competed for by parallel Gigawatt NPP and defence programs.",
        solution: ["Secured an exclusive mandate to supply licensing contractors with a minimum of two successful GDA negotiations each.", "Conducted 36 competency‑based interviews in four weeks; shortlisted 11 specialists.", "Oversaw contract mechanics, IR35 compliance, and rapid onboarding."],
        overCome: [" Eight contractors placed; all remain on assignment after two years, giving the client continuity through relevant GDA Steps.", "Reduced external legal review costs by embedding licensing expertise directly into project teams.", "Recognised by the client’s COO as their “most cost‑effective recruitment partner in the SMR space.\""],
    },
    {
        date: "2022 – present",
        title: "Global — Nuclear Fusion Startup (2022 – present)",
        client: "Early‑stage fusion company with R&D hubs in Tokyo (JP) and Reading (UK) ",
        challenge: " Hyper‑growth environment demanded cross‑border hiring and compensation structures that would attract both traditional fission talent and cutting‑edge plasma physicists.",
        solution: ["Delivered a global salary survey spanning 14 countries and three currency bands.", "Provided comparative analysis of equity incentives typical in deep‑tech start‑ups vs. established nuclear organisations.", "Placed engineers across mechanical design, high‑temperature superconducting magnets, and advanced manufacturing."],
        overCome: ["100 % of critical roles filled ahead of Series‑B funding announcement.", "Harmonised pay bands reduced offer renegotiations by 70 %.", "Ongoing partnership includes quarterly market‑pulse reports for the founder’s board deck."],
    },
    {
        date: "2019 – present",
        title: "United Kingdom — Multidisciplinary Engineering Consultancy (2019 – present)",
        client: " UK‑based EPC contractor active in new‑build and SMR projects",
        challenge: " The client sought a single external partner capable of covering everything from civil design to systems engineering during bid surges.",
        solution: ["Established preferred‑supplier status after outperforming three incumbent agencies on speed and quality.", "Embedded a TRX account manager inside the client’s Bristol office one day per week.", "Leveraged talent pools from our Saudi & Polish programs to cross‑pollinate best practice."],
        overCome: ["Average time‑to‑hire cut from 43 to 18 days.", "Over 60 placements across seven project sites; 98 % retention after one year.", "Commended by the Managing Director for “grasping our needs faster than any other supplier.\""],
    },
    {
        date: "2023",
        title: "Canada — SMR Start‑up Leadership Hires (2023)",
        client: "SMR technology start‑up headquartered in Ontario ",
        challenge: " The founders needed senior leaders who could operate in a lean start‑up but still satisfy CNSC regulatory rigor.",
        solution: ["Launched a rapid‑response search that delivered three slate candidates per role within seven days.", "Roles included Engineering Director, Procedure Writer (N286), and Operations Specialist.", "Managed reference checks across three continents and coordinated cross‑border relocation packages."],
        overCome: ["All three executives accepted within 30 days, securing leadership team completeness required for the next investment tranche.", "Post‑placement survey showed 9.6/10 satisfaction with hiring experience."],
    },
    {
        date: "2021 – present",
        title: "Germany — Decommissioning & Radioactive Waste Management (2021 – present)",
        client: "Tier‑1 German utility winding down its nuclear fleet ",
        challenge: "Niche expertise in decommissioning, paired with mandatory German‑language proficiency, made roles extremely hard to fill.",
        solution: ["Became exclusive recruitment partner after successfully staffing initial four positions others had failed to fill for six months.", "Deployed German‑speaking recruiters and hosted virtual job fairs to tap expatriate talent.", "Streamlined AÜG compliance for contingent hires."],
        overCome: ["50+ hires across engineering, radiological protection, and waste logistics.", "Reduced vacancy duration by 55 %, mitigating schedule delay penalties.", "Built a talent pipeline of German nationals for succession into permanent leadership posts."],
    },
    {
        date: "2018 – present",
        title: "France — ITER Fusion Project Support (2018 – present)",
        client: " Multiple contractors and research entities on the ITER site in Cadarache ",
        challenge: "ITER’s multinational ecosystem requires both permanent and contingent staff that can navigate complex safety regimes and cultural nuances.",
        solution: ["Created a central TRX‑managed talent pool for engineering & safety disciplines (nuclear analysis, cryogenics, RAMI).", "Coordinated with French labour authorities to manage work‑permit processes for non‑EU specialists.", "Implemented a shared services onboarding model that reduced duplication across multiple contractors."],
        overCome: ["Placed over 80 specialists (45% permanent, 55% contract) to date.", "Contractor bench has achieved a 97% extension rate—critical for continuity on multi‑year work packages.", "Recognised by ITER HR for “simplifying cross‑company resourcing and raising overall talent quality.”"]
    }
];